{{- if and .Values.profile.enabled .Values.readiness.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nvidia-ai-readiness.fullname" . }}
  labels:
    {{- include "nvidia-ai-readiness.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
